version: '3'
services:
  nextjs:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes: 
      - /app/node_modules
      - .:/app

  # ngnix:
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"

  prom-server:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - prometheus-storage:/etc/prometheus/

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    ports:  
      - "3000:3000"
    volumes:
      # - grafana-storage:/var/lib/grafana
      - grafana-storage:/var/lib/grafana

  grafana-loki:
    image: grafana/loki:latest
    container_name: grafana-loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    volumes:
      - loki-storage:/tmp/loki/
volumes:
  prometheus-storage:
  grafana-storage:
  loki-storage:
