version: '3'
services:
  nextjs:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    # ports:
    #   - "3000:3000"
    volumes: 
      - /app/node_modules
      - .:/app

  ngnix:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "3000:3000"