global:
  scrape_interval: 4s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["192.168.0.100:3000"]
      # target is the IP address of the machine running the node exporter (prom-client)