version: '3'
services:
  full-stack:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    volumes: 
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro